### ISSUE TITLE
Open to rehome plugin from @backstage to @circleci?

### ISSUE THREAD

**Issue by tudi2d** [CircleCI-Public/backstage-plugin#3]
Hi @EricRibeiro & @KyleTryon!

Great to see you working on improving the CircleCI Backstage plugin! We at Backstage are looking at ways to improve our current plugin maintenance model ([RFC](https://github.com/backstage/backstage/issues/20266)) & are especially grateful when organisations associated with the plugin are willing to take ownership. A recent example of this is the PageDuty plugin being "rehomed" https://github.com/backstage/backstage/issues/19347 or the Dynatrace plugin changing ownership https://github.com/backstage/backstage/pull/20224.

If you have any questions or are looking for support, please do not hesitate to contact us - we are always happy to talk about it & get feedback if you run into problems.

Have a great day & thanks for contributing to the community! :)

**Comment by KyleTryon** [comment]
Hello @tudi2d 
I believe we have already taken ownership of the plugin and republished it under our own NPM registry. I believe our teams may already be in contact via email

**Comment by tudi2d** [comment]
Ah thanks - great to hear! Are you good with me deprecating `@backstage/plugin-circleci` in our repository & changing the ownership in our[ Open Source Plugin directory](https://backstage.io/plugins/) to "CircleCI" to give it some visibility? :)

**Comment by tudi2d** [comment]
Created a draft PR to change existing references: https://github.com/backstage/backstage/pull/21104. Feel free to give feedback or let me know if we should wait with removing those references.

**Comment by EricRibeiro** [comment]
Thanks, @tudi2d!

Feel free to merge it. It's all good on our side.

**Comment by tudi2d** [comment]
thanks - it's merged - closing this now
